module.exports = [
  { username: 'ASmith', email: 'ASmith@gmail.com' },
  { username: 'AJohnson', email: 'AJohnson@yahoo.com' },
  { username: 'AWilliams', email: 'AWilliams@hotmail.com' },
  { username: 'ABrown', email: 'ABrown@outlook.com' },
  { username: 'AJones', email: 'AJones@company.org' },
  { username: 'AGarcia', email: 'AGarcia@school.edu' },
  { username: 'CMiller', email: 'CMiller@bureaucracy.gov' },
  { username: 'CDavis', email: 'CDavis@network.net' },
  { username: 'FRodriguez', email: 'FRodriguez@military.mil' },
  { username: 'GMartinez', email: 'GMartinez@domain.co' },
  { username: 'GHernandez', email: 'GHernandez@thebighouse.us' },
  { username: 'JLopez', email: 'JLopez@mailings.post' },
  { username: 'JGonzalez', email: 'JGonzalez@techblog.blog' },
  { username: 'KWilson', email: 'KWilson@aol.com' },
  { username: 'MAnderson', email: 'MAnderson@yahoo.com' },
  { username: 'NThomas', email: 'NThomas@hotmail.com' },
  { username: 'PTaylor', email: 'PTaylor@outlook.com' },
  { username: 'SMoore', email: 'SMoore@company.org' },
  { username: 'SJackson', email: 'SJackson@school.edu' },
  { username: 'SMartin', email: 'SMartin@bureaucracy.gov' },
  { username: 'TLee', email: 'TLee@network.net' },
  { username: 'TPerez', email: 'TPerez@military.mil' },
  { username: 'VThompson', email: 'VThompson@domain.co' },
  { username: 'XWhite', email: 'XWhite@thebighouse.us' },
  { username: 'ZHarris', email: 'ZHarris@mailings.post' },
];